insert into resort values(1001,'TREE OF LIFE RESORT','KACHERAWALA KOOKAS','JAIPUR',3,3.8,2);
insert into resort values(1001,'PALETTE RESORTS','LAKE VIEW ROAD NALLVADU POST','PONDICHERRY',2,4.3,2);
insert into resort values(1001,'GRAND GRT','SIR THEAGARAYA RD TNAGAR','CHENNAI',1,4.4,1);
insert into resort values(1001,'GREEN COCONUT','MAHABALIPURAM','CHENNAI',1,3.7,1);  
